version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start-dev
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
